"""Initial schema

Revision ID: 14918ebad988
Revises: 301587b90bfa
Create Date: 2026-06-06 16:08:10.418180

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

revision = '14918ebad988'
down_revision = '301587b90bfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata', sa.JSON(), nullable=True))
        batch_op.drop_column('metadata_')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata_', sqlite.JSON(), nullable=True))
        batch_op.drop_column('metadata')

    # ### end Alembic commands ###
